version: '3.8'

services:
    php:
        build:
            context: .
        container_name: php
        restart: unless-stopped
        ports:
            - 1233:80
            - 8001:8000
        volumes:
            - ./project:/var/www/html
            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
            - db
    db:
        image: mysql:8
        container_name: db
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: test_db
        volumes:
            - ./mysql-data:/var/lib/mysql
    pma:
        image: phpmyadmin/phpmyadmin:5.0.1
        container_name: pma
        restart: unless-stopped
        ports:
            - 1234:80
        environment:
            PMA_HOST: db
        depends_on:
            - db
    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - 6379:6379
        volumes:
            - ./redis-data:/data
    node:
        image: node:latest
        container_name: node
        restart: unless-stopped
        ports:
            - 4001:80